version: '3.7'

services:
  k6-node-1:
    image: grafana/k6
    volumes:
      - ./test:/test
      - ./reports:/reports
    entrypoint: ["k6", "run", "--out", "json=/reports/report-node-1.json", "/test/${SCRIPT}"]
    environment:
      - SCRIPT=${SCRIPT}

  k6-node-2:
    image: grafana/k6
    volumes:
      - ./test:/test
      - ./reports:/reports
    entrypoint: ["k6", "run", "--out", "json=/reports/report-node-2.json", "/test/${SCRIPT}"]
    environment:
      - SCRIPT=${SCRIPT}

  k6-node-3:
    image: grafana/k6
    volumes:
      - ./test:/test
      - ./reports:/reports
    entrypoint: ["k6", "run", "--out", "json=/reports/report-node-3.json", "/test/${SCRIPT}"]
    environment:
      - SCRIPT=${SCRIPT}

  k6-node-4:
    image: grafana/k6
    volumes:
      - ./test:/test
      - ./reports:/reports
    entrypoint: ["k6", "run", "--out", "json=/reports/report-node-4.json", "/test/${SCRIPT}"]
    environment:
      - SCRIPT=${SCRIPT}

  k6-node-5:
    image: grafana/k6
    volumes:
      - ./test:/test
      - ./reports:/reports
    entrypoint: ["k6", "run", "--out", "json=/reports/report-node-5.json", "/test/${SCRIPT}"]
    environment:
      - SCRIPT=${SCRIPT}
